baseURL: "https://elghazali.netlify.app"
languageCode: "en-us"
title: "Elghazali's Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
#     - identifier: blog
#       name: Blog
#       title: Blog posts
#       url: /blogs
#       weight: 1
#     - identifier: gallery
#       name: Gallery
#       title: Blog posts
#       url: /gallery
#       weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Elghazali's Profile"
  description: Know more about me!
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
     defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Elghazali's Portfolio" # Brand name for the brand | default is the title variable
    # disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, I am"
    title: "Mohamed Elghazali Kimeche."
    subtitle: "Cyber Security Enthusiast"
    content: "Computer science engineer with an obsession to every chip that makes a computer. Creative and passionate about cybersecurity, networking, and hardware, with diverse skills including pentesting, problem solving and troubleshooting, enthusiastic and curious about new technologies."
    image: /images/hero.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Elghazali-99
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/gzli/
      # customIcons:
      #   - icon: /linkedin.png
      #     url: "https://www.linkedin.com/in/gzli/"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/hero.png"
    content: |-
      I am a computer science engineer with a passion for cybersecurity, network security, digital forensics incident response. As an active CTF player, I thrive in CTF competitions with [OctaC0re team](https://ctftime.org/team/141485), continuously sharpening my skills in capturing flags and solving intricate challenges. 

      With a diverse skillset encompassing pentesting, problem solving, and troubleshooting, I am driven to secure digital landscapes against threats. Fuelled by enthusiasm and an insatiable curiosity, I remain at the forefront of emerging technologies, constantly seeking innovative solutions to safeguard and advance the digital realm.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Autopsy"
        - "Ghidra"
        - "Wireshark"
        - "Burp suite"
        - "Nessus"
        - "Docker"
        - "kubernetes"
        - "Python"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Internship - Graduation Project"
        company: "Montréal University"
        companyUrl: "https://www.umontreal.ca/en/"
        date: "October 2022 - July 2023"
        # featuredLink:
        #   enable: true
        #   name: "View the project"
        #   url: "https://example.com"
        content: "Privacy-Preserving by studying user behavior on a simulated social media platform."

      - job: "Phishing Campaign Simulation"
        company: "Realistic Security"
        companyUrl: "https://www.realistic-security.com/"
        date: "September 2021 - October 2021"
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"
        # info:
        #   enable: true
        #   content: I worked as a software developer for more than one year in Amazon.
        content: |
          Discover and simulate the different phishing techniques used by hackers.

      

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Computer science engineer"
        school:
          name: "École Nationale Supérieure d'Informatique - Algiers"
          url: "https://esi.dz"
        date: "2020 - 2023"
        # GPA: "3.8 out of 5.0"
        content: |-
          Specialized in computer systems:
            - Information Security, Artificial Intelligence, Computer Networks. 
            - Advanced Computer Architecture, Operating Systems, Database Systems.
            - Business economics.

          Extracurricular Activities:
            - Digital forensics workshop.
            - CTF author.
      - title: "Preparatory class in Computer Science"
        school:
          name: "École Supérieure en Informatique - Sidi Belabbes"
          url: "https://esi-sba.dz/"
        date: "2018 - 2020"
        # GPA: "3.9 out of 5.0"
        content: |-
          Foundational Courses:
          - Linear algebra, Mathematical analysis, Statistics, Probability.
          - Algorithms and Data Structures, Operating Systems, Computer Architecture, Object-oriented programming, Assembly.
          - Electricity, Electronics.

          Extracurricular Activities:
            - Graphic design workshops.
      #   featuredLink:
      #     enable: true
      #     name: "My academic record"
      #     url: "https://example.com"
      # - title: "High School"
      #   school:
      #     name: "Thomas Jefferson High School for Science and Technology."
      #     url: "https://example.org"
      #   GPA: "4.2 out of 5.0"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: CSAW’22 FINALS
        content: Qualified and ranked 7th in CSAW CTF Finals, the most comprehensive cybersecurity event.
        url: "https://www.csaw.io/"
      - title: 2022 - Capture the flag competitions
        content: 3rd place for "OctaC0re" on national level participating on more than 23 cybersecurity competitions over 2022.
        url: "https://ctftime.org/stats/2022/DZ"
      - title: 2021 - Capture the flag competitions
        content: 2nd place for "OctaC0re" on national level with more than 25 cybersecurity competitions over 2021.
        url: "https://ctftime.org/stats/2021/DZ"

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Cognicy
        content: A simulated social media platform for privacy awareness.
        image: /images/projects/Cognicy.png
        # featured:
        #   name: Demo
        #   link: https://hugo-profile.netlify.app
        badges:
          - "Privacy-preserving"
          - "Self-disclosure"
          - "Social media"
        # links:
        #   - icon: fa fa-envelope
        #     url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/hugo-profile
        #   - icon: fab fa-twitter
        #     url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: IPS / IDS System using RaspberryPi
        content: Log, monitor and Block malicious traffic by Intrusion Detection System and Intrusion Prevention System, implemented on a RasberryPi to secure and reduce the number of security incidents.
        image: /images/projects/raspberry.png
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "RaspberryPi"
          - "Snort"
          - "Linux"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/converter

      - title: EasyTP
        content: Deployment and administration of a Kubernetes cluster for TP management at ESI, by containerization and running the most used tools & softwares at the school inside a kubernetes cluster.
        image: /images/projects/Easytp.png
        # featured:
        #   name: Demo V2
        #   link: https://hugo-profile-2.netlify.app
        badges:
          - "Docker"
          - "Kubernetes"
          - "Django"
        links:
          - icon: fab fa-github
            url: https://github.com/TheDhm/EasyTP

      - title: VPN/MPLS platform (MP-BGP)
        content: Connect 6 sites of a company with a network operator, that has an IP backbone routed in MPLS. In order to insure connectivity to its remote sites and keeping its network confidential.
        image: /images/projects/mpls.png
        # featured:
        #   name: Demo V2
        #   link: https://hugo-profile-2.netlify.app
        badges:
          - "GNS3"
          - "MPLS"
          - "MP-BGP"
        
      - title: LAN / WAN network between two schools
        content: Provide assistance to two major engineering schools and two operators (a WAN operator and an ISP) for the implementation of a LAN/WAN network, based on VLAN, ROUTING, NAT, VPN.
        image: /images/projects/wan.webp
        # featured:
        #   name: Demo V2
        #   link: https://hugo-profile-2.netlify.app
        badges:
          - "Packet Tracer"
          - "VPN"
          - "NAT"

      - title: Edurika BOT
        content: Edurika is a chatbot that interacts with the student and provides him all the "BAC" topics (2008-2019) with the solution in PDF format.
        image: /images/projects/edurika.jpg
        # featured:
        #   name: Demo V2
        #   link: https://hugo-profile-2.netlify.app
        badges:
          - "Telegram‑bot API"
          - "Python"

      - title: StudentHub
        content: Developed an app that contribute to the degitization of the education sector of the algerian university.
        image: /images/projects/studenthub.png
        # featured:
        #   name: Demo V2
        #   link: https://hugo-profile-2.netlify.app
        badges:
          - "Java"
          - "Android"

  #Contact
  # contact:
  #   enable: true
  #   # title: "Custom Name"
  #   content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
  #   email: gurusabarisha@gmail.com
  #   btnName: Mail me
  #   # formspree:
  #   #   enable: true # `contact.email` value will be ignored
  #   #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
  #   #   emailCaption: "Enter your email address"
  #   #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/Elghazali-99
      linkedin: https://www.linkedin.com/in/gzli/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
